### ISSUE TITLE
RAM consumption high on server

### ISSUE THREAD

**Issue by PalgamingHD** [JayCeeCreates/earlygame#19]
java.lang.NoSuchMethodError: net.minecraft.class_1856.method_8105()[Lnet/minecraft/class_1799;
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removePlankRecipes$3(RecipeRemover.java:86) ~[earlygame-1.16.x-1.0.1.jar:?]
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$4(RecipeRemover.java:121) ~[earlygame-1.16.x-1.0.1.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_281]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281]
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$5(RecipeRemover.java:122) ~[earlygame-1.16.x-1.0.1.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[fabric-server-launch.jar:?]
	at jayceecreates.earlygame.utils.RecipeRemover.removeRecipes(RecipeRemover.java:117) ~[earlygame-1.16.x-1.0.1.jar:?]
	at jayceecreates.earlygame.utils.RecipeRemover.removePlankRecipes(RecipeRemover.java:83) ~[earlygame-1.16.x-1.0.1.jar:?]
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipe$0(RecipeRemover.java:39) ~[earlygame-1.16.x-1.0.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:48) ~[872199d5-c25b-4680-8a0e-3157f774f8bc.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cbd000$afterSetupServer(MinecraftServer.java:6243) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by PalgamingHD** [comment]
works fine on client

**Comment by JayCeeCreates** [comment]
YA BE

This is a big concern right there. I'll get into it-

**Comment by Merith-TK** [comment]
Any progress on this? I really want to use this in an SMP with a friend but it crashes on the server as stated here

**Comment by JayCeeCreates** [comment]
> Quoted from @Merith-TK:
Any progress on this? I really want to use this in an SMP with a friend but it crashes on the server as stated here

Hello! Thanks for following up on this issue!

Fret not, for this fix is already done. You can download the mod from here. Lemme know if you have any further inquiries, and I'll reopen the issue.
https://github.com/JayCeeCreates/earlygame/releases/tag/1.16.x-1.0.2

**Comment by JayCeeCreates** [comment]
EDIT: Updated the link

**Comment by Merith-TK** [comment]
I saw "fix was already done" in my notifications and immediately went "Oh cool! Time to build from source!"

But an official release that fixes it! Hell yes!

**Comment by JayCeeCreates** [comment]
> Quoted from @Merith-TK:
"Oh cool! Time to build from source!"

You need not build from source, for a binary is provided every release. You're welcome. :D

**Comment by Merith-TK** [comment]
Yeah new issue
It eats all the ram on the server

**Comment by JayCeeCreates** [comment]
Oof, I'll look into it-

**Comment by JayCeeCreates** [comment]
![image](https://user-images.githubusercontent.com/28774264/113496107-ed748900-9528-11eb-8fec-be2728f2f6ab.png)
@Merith-TK something like this?

**Comment by JayCeeCreates** [comment]
Care to share how it consumes a lot of RAM? @Merith-TK

**Comment by Merith-TK** [comment]
This is server-side only, I launch th server, and then at world Gen (or some startup near world Gen) the ram starts increasing in usage. Almost like a fork bomb or something.
The server usually runs at about 1.5-2gb ram idle,

With earlygame, it starts consuming more and more ram, going to 2.5, to 2.7, tp 3.2, 4, 5.4 (here is where j have to hardkill my entire server by manually pulling the plug because of a kernel panic from running out of ram.

https://cdn.merith.tk/assets/smp-boop-mekrath.zip

This is the server with the server.jar, fabric.jar,the mods, and configs. The earlygame mod is within the disabled folder inside of the mods folder

**Comment by Merith-TK** [comment]
have you figured out what went wrong yet?
—Merith

**Comment by JayCeeCreates** [comment]
Sorry I took a long time! I had to really focus on college and stuff so I had to take a break on modding ;;

Anyway, care to share the file again? Seems to have been deleted-

**Comment by Merith-TK** [comment]
Sorry! Will create a new zip for you!

https://cdn.merith.tk/assets/minecraft

Download the zip file. Mods are a bit out of date, but that is how it is
when the thing crashes,

**Comment by JayCeeCreates** [comment]
Thank you! Gonna look into it-

**Comment by JayCeeCreates** [comment]
![image](https://user-images.githubusercontent.com/28774264/117604746-c2fd9780-b188-11eb-9289-fe69fb2933ed.png)
Does something like this happen to you or something? @Merith-TK

**Comment by Merith-TK** [comment]
Yes, but after the third spike it just CONSUMES ALL THE RAM, like Kirby at an all you can eat buffet

**Comment by JayCeeCreates** [comment]
I actually left the server running and it doesn't seem to crash on me...

Probably from multiple players? Because right now I tested it on just one instance?

**Comment by Merith-TK** [comment]
How much ram are you telling it to use and how much ram do you have
installed?

I told it to use a max of around 5000mb, and hardware had around 7.5gb
usable.

**Comment by JayCeeCreates** [comment]
I launched it normally like an executable so I assume anything default? I have like 16 gigs

**Comment by JayCeeCreates** [comment]
Tried with and without the mod installed, I kinda barely don't see any difference at all? 🤔

**Comment by Merith-TK** [comment]
Odd... what the fuck?

**Comment by Merith-TK** [comment]
I have no clue why

set the server with these args 
`java -Xms1024M -Xmx3072M -jar fabric-server.jar`

Check if the ram usage (using task manager) peaks over 4gb
the menu that shows up has a tendency of reporting falsely due to not polling often enough

**Comment by JayCeeCreates** [comment]
This is the result 🤔
![image](https://user-images.githubusercontent.com/28774264/117755662-3d90ea80-b24f-11eb-8eac-df14fef3bb70.png)
It goes like above 2GB.

**Comment by JayCeeCreates** [comment]
and woah did this happen to you?
![image](https://user-images.githubusercontent.com/28774264/117756007-ed665800-b24f-11eb-8864-be49a83ef87d.png)
