### ISSUE TITLE
Block Render Layer Crash

### ISSUE THREAD

**Issue by Bonono63** [JayCeeCreates/earlygame#2]
Hello, I loaded your mod on my server and it crashed on start up.

The important part of the log is as follows:

=====

[19:35:05] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'earlygame'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/blockrenderlayer/v1/BlockRenderLayerMap
        at jayceecreates.earlygame.init.BlocksInit.init(BlocksInit.java:67) ~[earlygame-1.16.3-1.0.0a.jar:?]
        at jayceecreates.earlygame.EarlyGame.onInitialize(EarlyGame.java:28) ~[earlygame-1.16.3-1.0.0a.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at jayceecreates.earlygame.init.BlocksInit.init(BlocksInit.java:67) ~[earlygame-1.16.3-1.0.0a.jar:?]

======

I believe the issue is that you put the block render layer inside the main entrypoint in the mod and so the server tries to load it and can't.

I believe you need to put it inside a client entrypoint instead of the main entrypoint.

I'm to try and patch it myself to see if that fixes the problem, hopefully you can patch it officially so I can play it with some friends. Thanks!

**Comment by JayCeeCreates** [comment]
You're very much welcome to contribute to the project! I believe everything will improve as long as people work together~

This is my very first project as you can tell, and I have very little background with modding in general so I'm willing to be helped in any way possible!

**Comment by Bonono63** [comment]
I managed to fix it the server no longer crashes, but there appears to be yet another problem.

When I connect to the server I get:

Internal Exception: io.netty.handler.codec.EncoderException: Java.lang.NoSuchMethodError: jayceecreates.earlygame.utils.ModShapelessRecipe.method_8112()Ljava/lang/String;

Which put into human terms probably means that there is a missing method in the ModShapelessRecipe class,
I'm going to try and figure out which method that is, add it, and then see where it goes from there.

If you could also fix it that would be great.
I had to fork your project however to push the previous fix, I'm not sure how it works, but you might be able to accept the push into the main repo id you see no problems.

**Comment by Bonono63** [comment]
Fixed it and I pushed it to my fork, there are no more crashes and my client can connect to my server.

**Comment by JayCeeCreates** [comment]
Thanks for the fix! Closing the thread now~
