### ISSUE TITLE
Crash on Server, right after it finishes loading the world.

### ISSUE THREAD

**Issue by Cooliosity** [JayCeeCreates/earlygame#43]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7960()" because "recipeOutput" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
        at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$2(RecipeRemover.java:72) ~[earlygame-1.18.2-1.1.2.jar:?]
        at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$4(RecipeRemover.java:122) ~[earlygame-1.18.2-1.1.2.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1832) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$5(RecipeRemover.java:123) ~[earlygame-1.18.2-1.1.2.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1420) ~[?:?]
        at jayceecreates.earlygame.utils.RecipeRemover.removeRecipes(RecipeRemover.java:118) ~[earlygame-1.18.2-1.1.2.jar:?]
        at jayceecreates.earlygame.utils.RecipeRemover.removeRecipes(RecipeRemover.java:70) ~[earlygame-1.18.2-1.1.2.jar:?]
        at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipe$0(RecipeRemover.java:36) ~[earlygame-1.18.2-1.1.2.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.1.0+cc71601c60-e364e0bfc2b59ffc.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cog000$afterSetupServer(MinecraftServer:7812) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Cooliosity** [comment]
This crash also happens in single player. I think there might be some sort of incompatibility, I'll get back at you once I resolve it

**Comment by Cooliosity** [comment]
Well I just fixed it by removing the mod from my modpack, if you want me to do some testing or need more info just tell me

**Comment by JayCeeCreates** [comment]
What mods do you have in your modpack? And if you know what mod conflicts with EarlyGame, tell me~

**Comment by realguyman** [comment]
Please upload the latest log and crash files so we can take a look.

**Comment by realguyman** [comment]
Closing due to being stale. Open issue if more information is provided to hunt down the issue.
