### ISSUE TITLE
crash upon creating new world

### ISSUE THREAD

**Issue by zachnathan12** [JayCeeCreates/earlygame#45]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/31/22, 1:58 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7960()" because "recipeOutput" is null
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$2(RecipeRemover.java:72)
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$4(RecipeRemover.java:122)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipes$5(RecipeRemover.java:123)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at jayceecreates.earlygame.utils.RecipeRemover.removeRecipes(RecipeRemover.java:118)
	at jayceecreates.earlygame.utils.RecipeRemover.removeRecipes(RecipeRemover.java:70)
	at jayceecreates.earlygame.utils.RecipeRemover.lambda$removeRecipe$0(RecipeRemover.java:36)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$con000$afterSetupServer(MinecraftServer.java:4796)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by realguyman** [comment]
This doesn't help identify problem accurately. Please upload the full log and crash files as an attachment on GitHub.

**Comment by JayCeeCreates** [comment]
Also provide the full list of mods if you are using other feature mods-
